### ISSUE TITLE
[Improvement] Configure amount of displayed pagination links

### ISSUE THREAD

**Issue by jackd248** [studiomitte/solr_numbered_pagination#1]
Hej there,

is it possible to make the maximumNumberOfLinks configurable, so we can e.g. display only 5 links instead of the hardcoded 10? 

https://github.com/studiomitte/solr_numbered_pagination/blob/901bc03272cd43ff34e5f31915cd3a4e33369d3d/Classes/Slot/SolrResultActionSlot.php#L25

Cheers

**Comment by jackd248** [comment]
So maybe you can access the maxPageNumbers of the solr pagination? 

https://github.com/TYPO3-Solr/ext-solr/blob/release-11.5.x/Classes/Controller/SearchController.php#L120

```php
$maximumNumberOfLinks = ($values['pagination']->getMaxPageNumbers() ?: 10);
...
$values['pagination'] = GeneralUtility::makeInstance(NumberedPagination::class, $paginator, $maximumNumberOfLinks);
```

**Comment by georgringer** [comment]
Wanna do a pr?

**Comment by bernhardberger** [comment]
has this been verified to work? 

`plugin.tx_solr.results.maxPaginatorLinks = 5` still results in 10 pages as `$values['pagination']->getMaxPageNumbers()` always returns 0.
