### ISSUE TITLE
Call to undefined method BeforeSearchResultIsShownEvent::setPagination()

### ISSUE THREAD

**Issue by linawolf** [studiomitte/solr_numbered_pagination#3]
I just tried out dev-main of this version with apache-solr-for-typo3/solr 12.0.0-beta-1 unfortunary it seems like there is not method to set the pagination in `\ApacheSolrForTypo3\Solr\Event\Search\BeforeSearchResultIsShownEvent`

I did not find a work around unfortunary

**Comment by georgringer** [comment]
use IMO dev-main, see https://github.com/TYPO3-Solr/ext-solr/blob/4dd5d415e2c69bde292ac6ec8cd3f65cd5ad3cbd/Classes/Event/Search/BeforeSearchResultIsShownEvent.php#L83
