### ISSUE TITLE
TYPO3 12 release possible?

### ISSUE THREAD

**Issue by josefglatz** [studiomitte/solr_numbered_pagination#4]
Hi! I want to ask if a tag or maybe a release for TYPO3 12 will be possible to not rely on dev-main when using in TYPO3 12

**Comment by georgringer** [comment]
even solr is not yet released as stable version?!

**Comment by josefglatz** [comment]
👍 That's a valid and well-reasoned objection, which raises a pertinent point or concern worth considering in our discussion or decision-making process.

**Comment by georgringer** [comment]
done

**Comment by linawolf** [comment]
@josefglatz I believe, this ticket can be closed?

**Comment by georgringer** [comment]
released https://github.com/studiomitte/solr_numbered_pagination/releases/tag/1.0.3
